---
- name: Install munin, lighttpd and libcgi-fast-perl
  apt:
      update_cache: yes
      state: present
      pkg:
        - munin
        - munin-node
        - lighttpd
        - libcgi-fast-perl
