---
- name: Restart munin
  service:
    name: munin
    state: restarted

- name: Restart munin-node
  service:
    name: munin-node
    state: restarted

- name: Restart lighttpd
  service:
    name: lighttpd
    state: restarted